version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    command: npm run start
    volumes:
      - ./frontend:/var/app
    ports:
      - 3000:3000
